build: modify release action to be manually triggered
- version bump extension.yaml and manifest.yaml
- tag commit with version number

diff --git a/.github/workflows/generate-release.yaml b/.github/workflows/generate-release.yaml
--- a/.github/workflows/generate-release.yaml
+++ b/.github/workflows/generate-release.yaml
@@ -1,20 +1,31 @@
 name: Generate Extension Release
 
-run-name: "Generate Extension Release for ${{ github.ref_name }}"
+run-name: Generate Extension Release
 
 permissions:
   contents: write
 
 on:
-  push:
-    tags:
-      - 'v*'
+  workflow_dispatch:
+    inputs:
+      version:
+        description: Release version (format x.y.z)
+        required: true
 
 jobs:
-  build-hdr-manager:
-    name: Build Extension
+  generate-extension-release:
+    name: Generate Extension Release
     runs-on: windows-latest
     steps:
+      - name: Validate Version format
+        shell: pwsh
+        run: |
+          $version = "${{ github.event.inputs.version }}"
+          if ($version -notmatch '^\d+\.\d+\.\d+$') {
+            Write-Error "❌ Invalid version format: $version. Expected x.y.z"
+            exit 1
+          }
+
       - name: Checkout Repository
         uses: actions/checkout@v4
 
@@ -28,18 +39,58 @@ jobs:
         run: |
           npm install -g git-cliff
 
-      - name: Generate Changelog
+      - name: Generate Release Manifest Changelog
         shell: pwsh
         run: |
-          git-cliff --current --output CHANGELOG.md
+          git-cliff --current --config cliff.yaml.toml   --output YAML-CHANGELOG.txt
 
-      - name: Extract Version
-        id: version
+          if (-Not (Get-Content YAML-CHANGELOG.txt)) {
+              Write-Error "❌ There are no user-facing changes from which to generate a release"
+          }
+
+      - name: Install YAML Powershell Module
         shell: pwsh
         run: |
-          $tag = "${{ github.ref_name }}"
-          $version = $tag -replace "^v", ""
-          echo "version=$version" >> $env:GITHUB_OUTPUT
+          Install-Module powershell-yaml -Scope CurrentUser -Force
+          
+      - name: Update Extension Manifest
+        shell: pwsh
+        run: |
+          Import-Module powershell-yaml
+
+          $yaml = Get-Content extension.yaml | ConvertFrom-Yaml
+          $yaml.Version = "${{ github.event.inputs.version }}"
+          $yaml | ConvertTo-Yaml | Set-Content extension.yaml
+
+      - name: Update Release Manifest
+        shell: pwsh
+        run: |
+          Import-Module powershell-yaml
+
+          $newPackage = @{
+            Version = "${{ github.event.inputs.version }}"
+            RequiredApiVersion = "6.9.0"
+            ReleaseDate = (Get-Date -Format "yyyy-MM-dd")
+            PackageUrl = "https://github.com/lscholte/PlayniteHdrManager/releases/download/v${{ github.event.inputs.version }}/HdrManager_${{ github.event.inputs.version }}.pext"
+            Changelog = @(Get-Content YAML-CHANGELOG.txt)
+          }
+
+          $yaml = Get-Content manifest.yaml -Raw | ConvertFrom-Yaml
+          $yaml.Packages = @($newPackage) + $yaml.Packages
+          $yaml | ConvertTo-Yaml | Set-Content manifest.yaml
+
+      - name: Commit Manifest Changes
+        run: |
+          git config --global user.name "github-actions[bot]"
+          git config --global user.email "github-actions[bot]@users.noreply.github.com"
+
+          git add manifest.yaml extension.yaml
+          git commit -m "chore: bump version to ${{ github.event.inputs.version}}"
+          
+      - name: Tag Commit with Version
+        run: |
+          $version = "v${{ github.event.inputs.version }}"
+          git tag $version
 
       - name: Build Extension
         shell: pwsh
@@ -49,14 +100,23 @@ jobs:
       - name: Package Extension
         shell: pwsh
         run: |
-            Compress-Archive -Path bin/Release/* -DestinationPath HdrManager_${{ steps.version.outputs.version }}.pext -Force
+            Compress-Archive -Path bin/Release/* -DestinationPath HdrManager_${{ github.event.inputs.version }}.pext -Force
+
+      - name: Generate GitHub Release Changelog
+        shell: pwsh
+        run: |
+          git-cliff --current --config cliff.github.toml --output GITHUB-CHANGELOG.md
+
+      - name: Push Version Bump
+        run: |
+          git push
+          git push --tags
           
       - name: Create Release
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
-          gh release create ${{ github.ref_name }} `
-          --title "Version ${{ steps.version.outputs.version }}" `
-          --notes-file CHANGELOG.md `
-          --draft `
-          HdrManager_${{ steps.version.outputs.version }}.pext
+          gh release create v${{ github.event.inputs.version }} `
+          --title "Version ${{ github.event.inputs.version }}" `
+          --notes-file GITHUB-CHANGELOG.md `
+          HdrManager_${{ github.event.inputs.version }}.pext
